// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aymuxbbdrjroimlnwnqy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF5bXV4YmJkcmpyb2ltbG53bnF5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkwNTQ0ODUsImV4cCI6MjA3NDYzMDQ4NX0.lCweaXj--x3DhM7mbCszX7rK52eCFY1nHo9s-yU2wEc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});